# 12 projects @ 5,000 pods each creates 60,000 pods which fits into a 250 node cluster
provider: local
ClusterLoader:
  cleanup: true
  projects:
    - num: 12
      basename: clusterproject
      tuning: default
      ifexists: delete
      pods:
        - num: 5000
          image: gcr.io/google_containers/pause-amd64:3.0
          basename: pausepods
          file: pod-pause.json
  tuningsets:
    - name: default
      pods:
        stepping:
          stepsize: 150
          pause: 60
        ratelimit:
          delay: 0
