provider: local
ClusterLoader:
  cleanup: true
  projects:
    - num: 1000
      basename: project
      ifexists: reuse
      templates:
        -
          num: 1
          file: ./image-stream-template.json

        -
          num: 1
          file: ./deployment-config-ns-per-cluster-template.json
          parameters:
            -
              ENV_VALUE: "asodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij0emc2oed2ed2ed2e2easodfn209e8j0eij12"

        -
          num: 10
          file: ./ssh-secret-template.json
