provider: local
ClusterLoader:
  cleanup: true
  projects:
    - num: 1
      basename: clusterproject
      tuning: default
      ifexists: delete
      templates:
        -
          num: 10
          file: ./statefulset-pv-template.json

  tuningsets:
    - name: default
      pods:
        stepping:
          stepsize: 5
          pause: 10 s
        rate_limit:
          delay: 250 ms
