provider: local
ClusterLoader:
  cleanup: false
  projects:
    - num: 3
      basename: clusterloader0
      tuning: default
      ifexists: reuse
      pods:
        - num: 3000
          basename: stress-test
          file: pod-stress-simple.json
  tuningsets:
    - name: default
      pods:
        stepping:
          stepsize: 100
          pause: 5
        ratelimit:
          delay: 1
