kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "ycsb"
spec:
  template:
    metadata:
      labels:
        name: "ycsb"
    spec:
      containers:
        - name: "ycsb"
          image: "docker.io/hongkailiu/ycsb:002"
  triggers:
    - type: "ConfigChange"
  replicas: 1
