apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "two"
spec:
  limits:
    - type: openshift.io/Image
      max:
        storage: 200Mi
    - type: openshift.io/ImageStream
      max:
        openshift.io/image-tags: 1
        openshift.io/images: 1
