apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: img-template
objects:
  - kind: Image
    apiVersion: image.openshift.io/v1
    metadata:
      name: "${NAME}"
      creationTimestamp:
    dockerImageReference: registry.redhat.io/ubi8/ruby-27:latest
    dockerImageMetadata:
      kind: DockerImage
      apiVersion: '1.0'
      Id: ''
      ContainerConfig: {}
      Config: {}
    dockerImageLayers: []
    dockerImageMetadataVersion: '1.0'
parameters:
  - name: NAME
