apiVersion: v1
kind: Pod
metadata:
  name: static-hello
spec:
  containers:
    - image: "quay.io/openshifttest/hello-pod@sha256:04b6af86b03c1836211be2589db870dba09b7811c197c47c07fbbe33c7f80ef7"
      name: hello-pod