apiVersion: v1
kind: Service
metadata:
  name: server{{.Replica}}-{{.Iteration}}
  labels:
    app: server
spec:
  ports:
  - port: 8080
    name: web
  selector:
    app: server{{.Replica}}-{{.Iteration}}