apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: {{.storage_class}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi