---
apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-openshift
spec:
  replicas: 3
  selector:
    name: hello-openshift
  template:
    metadata:
      labels:
        name: hello-openshift
    spec:
      containers:
      - image: openshift/hello-openshift
        name: helloworld
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
