---
- hosts: all

  sudo: yes
  user: root
  tasks:
    - name: Backup master-config
      copy: src=/etc/origin/master/master-config.yaml dest=/etc/origin/master/master-config.yaml.before.conformance
    - name: Remove defaultNodeSelector
      replace: 
        path: /etc/origin/master/master-config.yaml
        regexp: 'defaultNodeSelector: .*'
        replace: 'defaultNodeSelector: ""'
    - name: Restart the static pod for api
      shell: /usr/local/bin/master-restart api
    - name: Restart the static pod for controllers
      shell: /usr/local/bin/master-restart controllers
