---
- hosts: all

  sudo: yes
  user: root
  tasks:
    - name: Backup master-config
      copy: src=/etc/origin/master/master-config.yaml dest=/etc/origin/master/master-config.yaml.before.conformance
    - name: Remove defaultNodeSelector
      replace: 
        path: /etc/origin/master/master-config.yaml
        regexp: 'defaultNodeSelector: .*'
        replace: 'defaultNodeSelector: ""'
    - name: Restart master services
      systemd:
        name: "{{ item }}"
        state: restarted
      with_items:
        - atomic-openshift-master-controllers
        - atomic-openshift-master-api

