---
- hosts: all

  sudo: yes
  user: root
  tasks:
    - name: Backup current master-config
      copy: src=/etc/origin/master/master-config.yaml dest=/etc/origin/master/master-config.yaml.after.conformance
    - name: Restore original master-config
      copy: src=/etc/origin/master/master-config.yaml.before.conformance dest=/etc/origin/master/master-config.yaml
    - name: Restart the static pod for api
      shell: /usr/local/bin/master-restart api
    - name: Restart the static pod for controllers
      shell: /usr/local/bin/master-restart controllers
