apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "pvc-{{.Replica}}"
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: {{.storageClassName}}
  volumeMode: Filesystem