projects:
  - num: 4
    basename: eap-
    tuning: default
    templates:
      - num: 1
        file: /root/svt/openshift_scalability/content/quickstarts/eap/eap64-mysql.json
        parameters: 
         - MEMORY_LIMIT: "0"

tuningsets:
  - name: default
    pods:
      stepping:
        stepsize: 5
        pause: 0 min
      rate_limit:
        delay: 0 ms