---
- name: clean yum cache
  shell:  yum clean all
  ignore_errors: true

- name: remove /root/.kube dir
  shell: /bin/rm -rf /root/.kube
  ignore_errors: true

- name: delete contents of directories /etc/origin/node and /etc/origin/master
  shell: /bin/rm -rf /etc/origin/node/*; /bin/rm -rf /etc/origin/master/*
  ignore_errors: true

## commented out, we do not want to remove openshift-ansible
## - name: ensure openshift-ansible is not installed
##   yum: name=openshift-ansible state=absent
