projects:
  - num: 1
    basename: svt-
    ifexists: delete
    tuning: default
    templates:
      - num: 1
        file: ./content/logtest/logtest-syslog-rc.json
        parameters:
         - REPLICAS: "0"
         - INITIAL_FLAGS: "--journal --num-lines 0 --line-length 200 --word-length 9 --rate 60 --fixed-line\n"

tuningsets:
  - name: default
    pods:
      stepping:
        stepsize: 5
        pause: 0 min
      rate_limit:
        delay: 0 ms
