projects:
  - num: 2
    basename: myconfig-
    tuning: default
    templates:
      - 
        num: 1
        file: ./content/woodshed-template.yaml
tuningsets:
  - name: default
    pods:
      stepping:
        stepsize: 5
        pause: 10 s
      rate_limit:
        delay: 250 ms
quotas:
  - name: default
