---
- hosts: master:sender:receiver
  become: true
  become_method: sudo
  user: root
  tasks:
    - name: Copy ssh public key to local systems
      copy: src=id_rsa.pub dest=/root/.ssh/.

- hosts: sender:receiver
  remote_user: root
  tasks:
  - name: Install openssh client and servers
    shell: yum install --assumeyes openssh-clients openssh-server

  - name: Yum clean-up
    shell: yum clean all

  - name: Enable epel
    shell: curl -o /etc/yum.repos.d/pbench.repo https://copr.fedorainfracloud.org/coprs/ndokos/pbench/repo/epel-7/ndokos-pbench-epel-7.repo

  - name: Install configtools, pbench-agent, pbench-uperf
    shell: yum install --assumeyes configtools pbench-agent pbench-uperf

  - name: Source pbench profile.
    shell: source /etc/profile.d/pbench-agent.sh

- hosts: master
  remote_user: root
  tasks:
  - name: Create SSH directory /root/.ssh if it does not exist
    file: path=/root/.ssh state=directory

  - stat: path=/root/.ssh/id_rsa
    register: id_rsa

  - name: Create /root/.ssh/id_rsa if it does not exist
    shell: ssh-keygen -f /root/.ssh/id_rsa -N ''
    when: id_rsa.stat.islnk is not defined

  - name: Register pbench tools on master
    shell: pbench-register-tool-set --label={{ pbench_label }}

  - name: Register pbench tools on remote
    shell: pbench-register-tool-set --label={{ pbench_label }} --remote={{ pbench_remote }}
    when: pbench_remote != "None"

  - name: Run pbench-uperf for TCP benchmarks
    shell: >
      pbench-uperf
      --test-types=stream,rr
      --runtime=30
      --message-sizes=64,1024,16384
      --protocols=tcp
      --instances=2
      --samples=3
      --max-stddev=10
      --clients={{ sender_host }}
      --servers={{ receiver_host }}
      --config={{ pbench_label }}_TCP

  - name: Run pbench-uperf for UDP benchmarks
    shell: >
      pbench-uperf
      --test-types=stream,rr
      --runtime=30
      --message-sizes=64,1024,16384
      --protocols=udp
      --instances=2
      --samples=3
      --max-stddev=10
      --clients={{ sender_host }}
      --servers={{ receiver_host }}
      --config={{ pbench_label }}_UDP

  - name: Copy pbench results
    shell: pbench-copy-results

  - name: Kill pbench tools
    shell: pbench-kill-tools

  - name: Clear pbench tools
    shell: pbench-clear-tools

  - name: Clear pbench results
    shell: pbench-clear-results
