---
- hosts: stac_nodes
  remote_user: root
  tasks:

  - name: install epel 7
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present

  - name: add rhel latest repos
    yum_repository:
      name: rhel_latest
      description: rhel 7.4 should be injected from outside
      baseurl: {{ rhel_repo }}

  - name: install reqiured pkgs
    yum: state=present name={{ item }}
      with_items:
      - kernel
      - kernel-devel
      - gcc
      - js
      - tuna
      - tuned
      - numactl
      - python34
      - rpmbuild

  - name: download openonload
    get_url:
      url: http://www.openonload.org/download/openonload-201606-u1.3.tgz
      dest: /root/

  - name: install openonload
    shell: rpmbuild -ta /root/openonload-201606-u1.3.tgz

  - name: remove onload archive
    file:
      path: /root/openonload-201606-u1.3.tgz
      state: absent

  - name: Create stac tuned profile directory if not exists
    file: path=/etc/tuned/stac state=directory
    
  - name: Copy tuned stac profile to producer and consumer
    copy: src=stac/tuned.conf dest=/etc/tuned/stac/tuned.conf

  - name: Copy stac profile script to producer and consumer
    copy: src=scripts/tuning.sh dest=/etc/tuned/stac/tuning.sh owner=root group=root mode=744

  - name: Update interface name in tuned script
    replace:
      dest=/etc/tuned/stac/tuning.sh
      regexp='<benchmark_interface>'
      replace={{ iface_name }}

  - name: Copy stac profile variables to nodes
    copy: src=stac/tuned_variables.conf dest=/etc/tuned/stac/tuned_variables.conf

  - name: Enable stac profile on nodes
    shell: tuned-adm profile stac

  - name: restart service tuned
    shell: systemctl restart tuned

  - name: Verify tuned stac profile on producer and consumer nodes
    shell: tuned-adm verify

