## JMeter Test Config
## Mention the parameters of each Jmeter Test that are needed to create a Jmeter Test Plan.
## Each test will have its own parameters.
## Each parameter set will correspond to one Jmeter test plan.

## Conditions:
##     1. Test Suite Name has to be unique, otherwise the test plan files will be overwritten.
##     1. Test Suite Name should not contain hyphens (-), used as a seperator for discribing the scenario
##     2. interval between app hits must be mentioned in milliSecs and all other time in Secs
##     3. app URL must be of the format http://<appurl>(optional < :port >)/path_to_resource
##     4. number of users, ramp up time, number of user loops, number of app loops and interval are all arrays.
## nodejs-mongodb-example-nodejs-11.1b7d.free-stg.openshiftapps.com

jmeterTestParameters:
   - testSuiteName: app1
     appURL: http://nodejs-mongodb-example-nodejs-mongodb0.0516-xhm.qe.rhcloud.com
     numberOfUsers: [100]
     rampUpTime: [0]
     numberOfUserLoops: [ 1 ]
     numberOfAppLoops: [130] 
     intervalBetweenAppHits: [200]