---
- block:
    - name: create directory to store pbench results, store openshift templates for pbench
      file: 
        path: "{{ item }}"
        state: directory
      with_items:
         - /var/lib/pbench-agent
         - /var/home/openshift-templates/pbench

    - name: copy openshift template for pbench
      copy: 
        src: pbench-agent-daemonset.yml  
        dest: /var/home/openshift-templates/pbench 
        owner: root 
        group: root 
        mode: 0644
  when: atomic | default(False) | bool
     
# not using docker_image module of ansible since that requires docker-py package to be installed on the atomic host
- name: pull pbench-agent from dockerhub
  command: docker pull ravielluri/image:agent

- name: pull pbench-controller image from dockerhub
  command: docker pull ravielluri/image:controller

- name: pull ycsb image from docker.io
  docker_image:
    name: docker.io/hongkailiu/ycsb
    tag: 0.15.0

- name: add token needed for uploading r2r results
  lineinfile:
    path: "/root/svt/utils/pbwedge/hosts"
    regexp: "github_token"
    line: "github_token={{ scale_ci_results_token }}"
  when: scale_ci_results_token is defined
