---
- name: install openshift packages
  yum: name={{ item }} state=latest
  with_items:
    - atomic-openshift-sdn-ovs
    - atomic-openshift-tests
    - atomic-openshift-node
    - atomic-openshift-pod
    - atomic-openshift-utils
    - atomic-openshift-clients
    - atomic-openshift-clients-redistributable
    - atomic-openshift-dockerregistry
    - tuned-profiles-atomic
    - tuned-profiles-atomic-openshift-node
    - atomic-openshift-docker-excluder
    - atomic-openshift-excluder

