---
- name: remove the currently installed ansible package which normally comes form epel or rhel-7-extras-next repos
  yum:
    name: ansible
    state: absent

- name: install ansible from rhel7-server-ansible.repo
  yum:
    name: ansible
    disablerepo: "*"
    enablerepo: rhel-7-server-ansible
    state: present

