apiVersion: v1
kind: Secret
metadata:
  name: SECRET_NAME
  namespace: NAMESPACE
type: Opaque
data:
  ssh-private-key: SSH_PRIVATE_KEY
  ssh-public-key: SSH_PUBLIC_KEY
  token: TOKEN_VALUE
  tls.crt: CERTIFICATE
  tls.key: PRIVATE_KEY
