---
- hosts: pbench-controller
  user: root
  tasks:
    - name: add endpoints to monitor
      shell: if [[ {{ use_certs | default(true) | bool }} ]]; then echo -e {{ item }} port=8443 cert=/etc/origin/master/admin.crt key=/etc/origin/master/admin.key >> {{ inventory_file }}; else echo -e host={{ item }} port=8443 >> {{ inventory_file }}; fi
      with_items:
       - "{{ groups['masters'] }}"
    - name: add endpoints to monitor
      shell: if [[ {{ use_certs | default(true) | bool }} ]]; then echo -e {{ item }} port=10250 cert=/etc/origin/master/admin.crt key=/etc/origin/master/admin.key >> {{ inventory_file }}; else echo -e host={{ item }} port=10250 >> {{ inventory_file }}; fi
      with_items:
       - "{{ groups['masters'] }}"
       - "{{ groups['nodes'] }}"
