{
 "title": "vSphere CSI",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Storage operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (operation_name, le) (rate(storage_operation_duration_seconds_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "CNS Metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (optype, le) (rate(vsphere_cns_volume_ops_histogram_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "vsphere csi ops",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (optype, le) (rate(vsphere_csi_volume_ops_histogram_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Full Sync",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (optype, le) (rate(vsphere_full_sync_ops_histogram_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Operation Failure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(optype) (vsphere_csi_volume_ops_histogram_count{status=\"fail\"})",
     "legendFormat": "csi-fail(optype={{optype}})"
    },
    {
     "expr": "sum by(optype) (vsphere_cns_volume_ops_histogram_count{status=\"fail\"})",
     "legendFormat": "cns-fail(optype={{optype}})"
    },
    {
     "expr": "sum by(operation_name) (storage_operation_duration_seconds_count{status=\"fail-unknown\"})",
     "legendFormat": "ocp({{operation_name}})"
    }
   ]
  }
 ]
}