---
- hosts: masters[0]
  user: root
  vars:
    - tooling_inv: /root/tooling_inventory
    - register_all_nodes : False
    - oc_client_url: "https://github.com/openshift/origin/releases/download/v1.2.1/openshift-origin-client-tools-v1.2.1-5e723f6-linux-64bit.tar.gz"
  tasks:
    - name: create openshift directory
      file:
        path: /run/openshift
        state: directory

    - name: copy, set permissions on the register script
      copy:
        src: generate.sh
        dest: /run/openshift/generate.sh
        owner: root
        group: root
        mode: 0755
    
    - name: label cns nodes
      shell: oc label node {{ item }} node-role.kubernetes.io/cns=true
      with_items:
       - "{{ groups['glusterfs'] }}"
      when: groups['glusterfs']|default([])
      ignore_errors: true

    - name: get the local hostname
      command: hostname
      register: ansible_controller 
      delegate_to: localhost
  
    - name: label nodes
      shell: sh /run/openshift/generate.sh {{ tooling_inv }} {{ register_all_nodes }} {{ oc_client_url }} {{ ansible_controller.stdout }}

    - name: copy the inventory onto jump host
      shell: scp {{ inventory_hostname }}:{{ tooling_inv }} {{ tooling_inv }}
      delegate_to: localhost
