apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-perf
  name: http-perf
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  type: NodePort
  