apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: descheduler-template
objects:
- kind: KubeDescheduler
  apiVersion: operator.openshift.io/v1
  metadata:
    name: cluster
    namespace: "${DESCH_NAMESPACE}"
  spec:
    deschedulingIntervalSeconds: ${{INTERSECONDS}}
    image: "${IMAGEINFO}"
    mode: Automatic
    logLevel: "${LOGLEVEL}"
    operatorLogLevel: "${OPERATORLOGLEVEL}"
    profiles:
      - "${PROFILE1}"
      - "${PROFILE2}"
    managementState: Managed
parameters:
- name: DESCH_NAMESPACE
- name: INTERSECONDS
- name: IMAGEINFO
- name: LOGLEVEL
- name: OPERATORLOGLEVEL
- name: PROFILE1
- name: PROFILE2
