apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: descheduler-template
objects:
- apiVersion: operator.openshift.io/v1
  kind: KubeDescheduler
  metadata:
    name: cluster
    namespace: "${DESCH_NAMESPACE}"
  spec:
    deschedulingIntervalSeconds: ${{INTERSECONDS}}
    image: "${IMAGEINFO}"
    logLevel: "${LOGLEVEL}"
    mode: Automatic
    operatorLogLevel: "${OPERATORLOGLEVEL}"
    profiles:
      - "${PROFILE1}"
    profileCustomizations:
      devLowNodeUtilizationThresholds: {UTILIZATION_THRESHOLD}
parameters:
- name: DESCH_NAMESPACE
- name: INTERSECONDS
- name: IMAGEINFO
- name: LOGLEVEL
- name: OPERATORLOGLEVEL
- name: PROFILE1
- name: UTILIZATION_THRESHOLD